ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "home_district" TEXT;
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "home_club_name" TEXT;
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "ry_year" INTEGER DEFAULT 2026;
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "edition" TEXT DEFAULT 'delhi_meri_jaan_2026';
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "rotary_id" TEXT;
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "city_state" TEXT DEFAULT 'Delhi NCR';
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "country" TEXT DEFAULT 'India';
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "club_designation" TEXT;
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "dietary_pref" TEXT DEFAULT 'veg';
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "allergies_notes" TEXT;
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "emergency_name" TEXT DEFAULT 'Emergency Contact';
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "emergency_phone" TEXT DEFAULT '+91 99999 99999';
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "emergency_relation" TEXT DEFAULT 'Guardian';
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "arrival_at" TIMESTAMP(3);
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "arrival_number" TEXT;
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "departure_at" TIMESTAMP(3);
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "host_club_id" TEXT;
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "host_family_name" TEXT;
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "host_family_phone" TEXT;
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "host_address" TEXT;
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "payment_status" TEXT DEFAULT 'pending';
ALTER TABLE "ride_participants" ADD COLUMN IF NOT EXISTS "payment_ref" TEXT;
ALTER TABLE "ride_participants" ALTER COLUMN "status" TYPE TEXT;
ALTER TABLE "ride_participants" ALTER COLUMN "status" SET DEFAULT 'submitted';
ALTER TABLE "ride_participants" ALTER COLUMN "participant_type" TYPE TEXT;
ALTER TABLE "ride_participants" ALTER COLUMN "participant_type" SET DEFAULT 'external';
