export const PERMISSIONS: Record<string, string> = {
  'profile:edit': 'Edit own member profile',
  'directory:view': 'View the member directory',
  'showcase:submit': 'Submit projects to the showcase',
  'showcase:publish': 'Edit and publish showcase projects',
  'reports:submit': 'Create and submit monthly reports',
  'reports:review': 'Review reports and raise queries',
  'reports:score': 'Score reports and award judged points',
  'requests:manage': 'Manage report form schemas and report requests',
  'members:approve': 'Approve, reject and suspend members',
  'members:import': 'Import members from CSV',
  'members:view': 'List members',
  'roles:manage': 'Manage roles, permissions and user roles',
  'content:edit': 'Edit content block drafts',
  'content:publish': 'Publish content blocks',
  'point_rules:manage': 'Manage point rules and tiers',
  'club_facts:edit': 'Edit yearly club facts',
  'effort:log': 'Log effort on behalf of members',
  'effort:approve': 'Approve self-logged effort',
  'events:manage': 'Manage district events',
  'events:checkin': 'Check members in to events',
  'club_events:log': 'Log club events',
  'feedback:submit': 'Submit feedback',
  'feedback:review': 'Review and reply to feedback',
  'announcements:send': 'Send announcements within scope',
  'announcements:send_all': 'Send announcements to the whole district',
  'settings:manage': 'Manage district settings',
  'drr_calendar:manage': 'Manage the DRR calendar and bookings',
  'audit:view': 'View the audit log',
  'clubs:view': 'View clubs',
  'clubs:edit': 'Edit club details and board',
  'resources:manage': 'Manage resources',
  'public_content:manage': 'Manage public content tables',
  'subdomain:mission3011:manage': 'Manage Mission 3011',
  'subdomain:drishti:manage': 'Manage Drishti',
  'subdomain:rcl:manage': 'Manage RCL',
  'subdomain:careerbridge:manage': 'Manage Career Bridge',
  'subdomain:ride:manage': 'Manage RIDE',
};

export const PROJECT_KEYS = ['mission3011', 'drishti', 'rcl', 'careerbridge', 'ride'] as const;
