export const SETTINGS: Record<string, unknown> = {
  'report.deadlineDay': 5,
  'compliance.thresholdMonths': 2,
  'feedback.allowAnonymous': false,
  'drr.workingDays': [1, 2, 3, 4, 5, 6],
  'drr.dayStart': '10:00',
  'drr.dayEnd': '19:00',
  'drr.slotMinutes': 60,
  'drr.bufferMinutes': 30,
  'drr.monthsAhead': 9,
  'drr.blackoutDates': [],
  'subdomain.mission3011.active': false,
  'subdomain.mission3011.leadClubId': null,
  'subdomain.drishti.active': false,
  'subdomain.drishti.leadClubId': null,
  'subdomain.rcl.active': false,
  'subdomain.rcl.leadClubId': null,
  'subdomain.careerbridge.active': false,
  'subdomain.careerbridge.leadClubId': null,
  'subdomain.ride.active': false,
  'subdomain.ride.leadClubId': null,
  enquiry_routing: {
    new_club: { name: '', email: '' },
    sponsor: { name: '', email: '' },
    contact: { name: '', email: '' },
  },
  'rcl.pointsWin': 2,
  'rcl.pointsTie': 1,
  'rcl.season': 2026,
  'careerbridge.expiryDays': 45,
  'home.stats': { zones: 4, focusAreas: 7, foundedYear: 1968, ageRange: '18–30' },
  'sponsor.ratios': { perRupee: 1, mealsPerThousand: 40, kitsPerThousand: 8, unitsPerThousand: 2 },
};
